[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/morph_analyses"]

[project]
name = "plittgiocomo-ca1morph-2019"
version = "0.1.0"
description = "Analysis of CA1 morphology data"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
requires-python = "==3.11.14"
dependencies = [
    "numpy",
    "scipy",
    "scikit-learn",
    "matplotlib",
    "pandas==3.0.2",
    "astropy",
    "ipython",
    "jupyter",
    "pynwb",
    "dandi",
    "h5py",
    "two_photon_utils",
    "nwbinspector",
    "seaborn",
    "umap-learn",
]

[tool.uv.sources]
two-photon-utils = { git = "https://github.com/GiocomoLab/TwoPUtils.git", rev = "48672c9f61adb737869cba9ff72f255ebdd77c69" }
nmftools = { git = "https://github.com/ahwillia/nmftools"}

[project.optional-dependencies]
scratch = [
    "umap-learn",
    "suite2p",
    "imageio",
    "opencv-python",
]